Feat update message type of /livox/lidar to sensor_msgs/PointCloud2
CIT-Autonomous-Robot-Lab/raspicat_documentation pull request #83
Opened 2023-10-04 07:50 UTC by IkuoShige

`/livox/lidar`トピックのメッセージ型を`livox_ros_driver2/msg/CustomMsg`から`sensor_msgs/msg/PointCloud2`に設定するセクションを追加しました。

2023-10-04 08:48 UTC, IkuoShige commented
@uhobeike レビューお願いします

2023-10-25 10:27 UTC, uhobeike requested changes
修正よろしくおねがいします。

2023-10-25 10:27 UTC, uhobeike commented on docs/document/real_machine/set_up/livox.md
> +    ### 3.4 msg_MID360_launch.pyの変更
msg_MID360_launch.pyにリンクをつけてくれると助かります。

[msg_MID360_launch.py](https://github.com/Livox-SDK/livox_ros_driver2/blob/master/launch_ROS2/msg_MID360_launch.py)

2023-10-26 03:57 UTC, IkuoShige commented
リンクを埋め込む修正を行いました。

2023-11-26 11:33 UTC, uhobeike approved these changes
良さそうです
マージをお願いします

2023-11-26 11:42 UTC, merged