Feat create Raspberry Pi clone and restore manual with commands and scripts
CIT-Autonomous-Robot-Lab/raspicat_documentation pull request #84
Opened 2023-10-19 15:33 UTC by IkuoShige

ラズパイのディスクをクローンし、リストアするドキュメントを作成しました。
また、クローン、リストアをCUIで行うためのスクリプトも追加しました。

2023-10-19 15:34 UTC, IkuoShige commented
@uhobeike レビューお願いします。

2023-10-25 10:40 UTC, uhobeike requested changes
修正よろしくおねがいします。

2023-10-25 10:40 UTC, uhobeike commented on mkdocs.yml
> +      - バックアップイメージの取得とリストア: document/realmachine/clone_restore.md
パスが間違ってます。
ので、ページがみれないですー。

正しくは、
`document/real_machine/clone_restore.md`

2023-10-25 10:40 UTC, uhobeike commented on docs/document/real_machine/clone_restore.md
> +summary: Raspberry Pi のバックアップとリストア
Raspberry Pi のSDカードのバックアップとリストア
の方が良いかな？

2023-10-25 10:40 UTC, uhobeike commented on docs/document/real_machine/clone_restore.md
> +# Raspberry Piのクローン
Raspberry Pi のSDカードのクローン
の方が良いかな？

2023-10-26 04:23 UTC, IkuoShige commented
修正しました。

2023-11-26 11:36 UTC, uhobeike approved these changes
多分、大丈夫です
マージお願いします

2023-11-26 11:51 UTC, merged